### ISSUE TITLE
[Improvement] Add graph to view glucose dynamics

### ISSUE THREAD

**Issue by SergeyRock** [dabear/FloatingGlucose#12]
It`ll be usefull to see sugar level dynamics in time.
Could do you add this feature for Nightscout URL option?

**Comment by dabear** [comment]
Thanks for the feedback, really appreciate it! However, there is currently no plan to implement this, as the widget is limited in amount of characters it can show. This would require either substantial rewrites, or implementing it as a dynamic background.

**Comment by SergeyRock** [comment]
Hello!
If you're intrested in I've wrote another app to see what I wanted:
[https://github.com/SergeyRock/nightscout-watcher](https://github.com/SergeyRock/nightscout-watcher)
Could you do a small review of that?
PS. Sorry for my English I'm not a native speaker...
