### ISSUE TITLE
Refreshing interval limit of 100 sec

### ISSUE THREAD

**Issue by nlof** [dabear/FloatingGlucose#13]
The GUI refresh interval cannot be increased to more than 100 sec. It may be helpful to allow increases to at least 300 seconds (5 minutes) as that is the interval at which nightscout receives updates from Dexcom...
Thank you in advance.

**Comment by dabear** [comment]
Thanks for your report. If the glucosedata value Comes in a bit late (for whatever reason) and by allowing intervals up to 300 seconds you could risk that the displayed glucose value is not up to date for the next 5 minutes. For the same reason I considered a Max of 60 seconds actually

**Comment by nlof** [comment]
I don't like hammering the server every 60-100 sec if the info only gets refreshed every 5 minutes.. Doing it 24/7 and from multiple devices doesn't look good...
I think you should allow flexibility on part of the user and not restrict the options, obviously everyone can change the refresh rate to whatever fits him...
