### ISSUE TITLE
Api-Tokens

### ISSUE THREAD

**Issue by blocklist** [dabear/FloatingGlucose#2]
Hi,

is it possible, to add in the Settings a field for an Token?
Then you can set Nightscout to only "readable" or "denied" and can load with:
https://nightscout-site.tld/api/v1/xxxx.json?token=$settings.token
or
https://nightscout-site.tld/?token=$settings.token
the Data from protected sites?

**Comment by dabear** [comment]
No, unfortunately. This is not supported and would have to be coded. No
time for that in December.

**Comment by n0rb33r7** [comment]
It would be really useful feature.

**Comment by dabear** [comment]
Regard this project as in maintance mode; I am not actively developing new features :)

**Comment by jees1234** [comment]
Hello, for everyone who may be interested I was able to make FloatingGlucose to support Nightscout API token authentication. It's actually pretty easy to modify the source code - just make changes into these two files:

NightscoutPebbleEndpoint.cs
---------------------------
namespace FloatingGlucose.Classes.DataSources.Plugins
{
    internal class NightscoutPebbleEndpoint : IDataSourcePlugin
    {
        public virtual bool RequiresUserNameAndPassword => true;
...

Note: This enables Username and Password dialog in Settings for Nightscout URL plugin.

FloatingGlucose.cs
------------------
private NameValueCollection datasourceLocation
        {
            get
            {
                // With raw glucose display we need to have two
                // data points to calculate raw glucose diff
                var count = Default.EnableRawGlucoseDisplay ? 2 : 1;
                var units = Default.GlucoseUnits;
                var urlstripped = Default.DataPathLocation.TrimEnd('/');
                var username = Default.UserName;
                return new NameValueCollection()
                {
                    { "raw", Default.DataPathLocation },
                    { "location", $"{urlstripped}/pebble?count={count}&units={units}&token={username}"}
                };
            }
        }

private void openNightscoutSiteToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var url = Default.DataPathLocation.TrimEnd('/');
            var username = Default.UserName;
            url += $"/?token={username}";
...

Compile the project in MS Visual Studio.
Then in FloatingGlucose Settings add API Token in Username dialog box, leave Password dialog empty. Now it should be possible to retrieve data from API token authentication enabled Nightscout site.
It works pretty well for me.

**Comment by dabear** [comment]
Hi. Could you create a Pull request? IT should also be possible to Rename the username field to "api token"

**Comment by jees1234** [comment]
Pull request with some additional changes (change "User Name" to "Access Token" in Settings window when Nightscout URL plugin is selected) has been created.
