### ISSUE TITLE
FloatingGlucose on Raspberry Pi

### ISSUE THREAD

**Issue by bordeb** [dabear/FloatingGlucose#3]
First of all, dear @dabear thank you VERY much on this great small but highly useful app! We use it on our home HTPC so even while watching videos we can still take a look at BG level! Great and tnx once more!
I have one question: Are there suggestions about how to implement this on RPi? I think this could be very usefull for T1D community, especially as there is already projects using RPi with wixel, like [python-usb-wixel-xdrip](https://github.com/jamorham/python-usb-wixel-xdrip) etc.
Is porting to an arm linux environment possible (needed) or maybe ExaGear Desktop with Wine on RPi or...? Thanks very much in advance on any suggestion?

**Comment by dabear** [comment]
If you can run wine successfully and you are able to install microsoft .net 4.5.1 inside wine(using winetricks for example), then yes, it works.  See https://github.com/dabear/FloatingGlucose/releases/tag/v.1.5.1 . It's not supported with mono natively on linux.
