### ISSUE TITLE
Nightscout URL just shows N/A

### ISSUE THREAD

**Issue by kvnsmn** [dabear/FloatingGlucose#4]

**Comment by dabear** [comment]
remove any password protection. the app doesn't support passwords for nightscout

**Comment by Barajott** [comment]
I got the same problem. There ist no password on my nightscout page but i can only see N/A on the plug in. 
In the nightscout URL i put in: 

https://mynightscoutname.herokuapp.com/


is this correct?

**Comment by dabear** [comment]
Yes, that should be correct. Make sure you haven't localized (changed language) on your nightscout installation. Sometimes this affects how the dates are formatted when programmatically accessing nightscout. If that clears out as well, contact me with your nightscout address, and I can look into it. I'm available on gitter under the same handle.

**Comment by Barajott** [comment]
Hey, where can i change the language in nightscout? on my mac at home it shows german and on my pc at work (win 10) it shows english. 

My Region on Heroku is Europe. i have no idea where i can change this.

**Comment by Barajott** [comment]
Got it!

i changed the time set from "**time**" "**24**" to "**12**" and add on heroku "**language**" "**en**". Now it works!! 

Thank you so much!!! 

How can i donate something for the great work?

**Comment by dabear** [comment]
Nice to hear that it worked out for you. I don't generally accept donations.
