### ISSUE TITLE
Crashes approximately once a fortnight

### ISSUE THREAD

**Issue by WanaGo** [dabear/FloatingGlucose#5]
Hi. Working great, thanks for making this. I have had exception errors come up approximately once a fortnight since I have had this installed though. (I leave my PC on 24/7). I was meaning to take a screenshot of the error but I closed it. Restarting it at that point and it's away again no problem, but there must be something up for it to do this.
Running Windows 10 x64 here. When it happens next ill add to this post.

**Comment by dabear** [comment]
thanks. Also post output from yournightscoutsite.com/api/v1/entries.json?count=100 while this problem occurs (pastebin it)

Most exceptions should be handled by the app, and if you see an unhandled exception triggeringa message box, clicking "continue" should work. It would also help if you can follow these instructions next time you start the app, and wait for the error to happen: https://github.com/dabear/FloatingGlucose#debugging 
Please pastebin the log as well together with an indication for when the problem occurs.

**Comment by WanaGo** [comment]
Yep I have already done the debugging page stuff and have that logging now. 
Clicking continue lets the app carry on yes, but it will crash again soon after with the same exception. Closing it and restarting it seems to be the only way for it to carry on successfully.
Ill do the above when it next happens. 
Thanks

**Comment by WanaGo** [comment]
Happened again.

Copied the error out of the Microsoft .NET Framework box, as well as a screenshot of that box, then the glucose_log file that was enabled, and the last 100 entries from my site.

![image](https://user-images.githubusercontent.com/759846/55530994-f5fd1380-5704-11e9-87fa-0614c430a8cc.png)

[glucose_log.txt](https://github.com/dabear/FloatingGlucose/files/3041854/glucose_log.txt)
[entries100.txt](https://github.com/dabear/FloatingGlucose/files/3041855/entries100.txt)
[exceptionMSNetFramework.txt](https://github.com/dabear/FloatingGlucose/files/3041863/exceptionMSNetFramework.txt)

Hope that helps

**Comment by dabear** [comment]
Seems this is related to timeout on the network or remote host (your nightscout installation).  What do you think would be the best solution to this? Fail silently, let the gui keep the old values, or fail silently, but invalidate the gui (eg. display N/A instead of the actual glucose value)

**Comment by fezulin** [comment]
I would prefer to display "N/A". Else the GUI shows a specific value, that is likely to be outdated.

**Comment by WanaGo** [comment]
Yep, anything is better than a crash :) Strange how its always about a fortnight between crashes, and when it happens I am sitting in front of my computer, on wifi, with my phone next to me, Dexcom on my arm etc, so no real reason for there to be a network issue on my end at least.

**Comment by WanaGo** [comment]
Crashed again.
In the log, it refers to this path:
E:\Kode\prosjekter\FloatingGlucose\FloatingGlucose\Classes\DataSources\Plugins\NightscoutPebbleEndpoint\NightscoutPebbleEndpoint.cs
This I assume is your development path on your PC. Curious why its showing in the log on my machine, as no such path exists obviously.

**Comment by dabear** [comment]
Please try the new version:
https://github.com/dabear/FloatingGlucose/releases/tag/v1.5.3

(Btw, Regarding the paths, I have no idea.)
